### ISSUE TITLE
NitroModules compilation fails on macOS Tahoe + Xcode 26.2 - PropNameIDCache not found

### ISSUE THREAD

**Issue by thegdsks** [jpudysz/react-native-unistyles#1076]
## Environment
- **react-native-unistyles**: 3.0.22
- **react-native-nitro-modules**: 0.31.10
- **Expo SDK**: 54
- **React Native**: 0.81.5
- **Xcode**: 26.2 (Build 17C52)
- **macOS**: Tahoe 26
- **newArchEnabled**: false (also tried true)

## Error

```
node_modules/react-native-unistyles/nitrogen/generated/shared/c++/Dimensions.hpp:28:2: error: NitroModules cannot be found! Are you sure you installed NitroModules properly?
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?

node_modules/react-native-unistyles/nitrogen/generated/shared/c++/Dimensions.hpp:63:73: error: use of undeclared identifier 'PropNameIDCache'
        JSIConverter<double>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "width"))),
                                                                        ^
```

Same errors in `Insets.hpp` for all `PropNameIDCache` references.

## Steps to Reproduce

1. Create Expo 54 project on macOS Tahoe
2. Install `react-native-unistyles@3.0.22`
3. Run `npx expo run:ios`

## What I've Tried

- [x] Clean install (`rm -rf node_modules ios/Pods && npm install`)
- [x] Clear Xcode DerivedData
- [x] Set `newArchEnabled: false`
- [x] Set `SWIFT_ENABLE_EXPLICIT_MODULES: NO` in expo-build-properties
- [x] Upgraded to latest unistyles (3.0.22) and nitro-modules (0.31.10)
- [x] Using Xcode 26.2 (latest release for macOS Tahoe)

## Expected Behavior

Build should complete successfully with NitroModules headers properly linked.

## Workaround

Downgrading to unistyles v2 (which doesn't use NitroModules) is the only workaround.

## Additional Context

This appears to be a header path/module compilation issue where the NitroModules C++ headers (specifically `PropNameIDCache.hpp`) are not being found during the unistyles compilation phase, even though NitroModules is installed and its own compilation succeeds.

The app works fine on physical device with Expo Go (which doesn't compile native code), confirming the issue is specific to native iOS builds.

**Comment by jpudysz** [comment]
You need to use at least the same version (or higher) of nitro modules that are mentioned in the README.

**Comment by thegdsks** [comment]
Thanks for the quick response! 

I verified the versions - we're using react-native-nitro-modules@0.33.2 which matches the README.

The issue seems specific to **Xcode 26.2** (beta) on **macOS Tahoe (26.x)**. The C++ compilation errors in PropNameIDCache.hpp suggest the newer Xcode toolchain handles some C++ syntax differently.

We worked around it by downgrading to Unistyles v2, but wanted to report this for others who might hit the same issue with the latest Xcode.

Environment:
- macOS Tahoe 26.x
- Xcode 26.2 (26B5105n)
- react-native-nitro-modules: 0.33.2
- Expo SDK 54
- React Native 0.81.5

**Comment by jpudysz** [comment]
Thanks for the clarification. I use 26.0.2, and I'm upgrading to 26.2.0 now.

Will report back.

**Comment by jpudysz** [comment]
Works correctly with Xcode 26.2.0

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/faaa7b22-cf0c-44a1-be8a-1bbf973d555f" />
